### ISSUE TITLE
Document pins for Pro Mini

### ISSUE THREAD

**Issue by ReallyNiceGuy** [PaulStoffregen/AltSoftSerial#2]
Hi, could you please add the Arduino Pro Mini pins on the documentation and example?
It is the same as the Arduino Uno. This would make it easier for the end user.

Thanks

**Comment by entozoon** [comment]
I second this.
Or ideally make it allow custom pins!

**Comment by PaulStoffregen** [comment]
I do not understand what you are asking.  Can you be more specific?

Is this only about adding extra words to the comment on this line?

https://github.com/PaulStoffregen/AltSoftSerial/blob/master/config/AltSoftSerial_Boards.h#L83

**Comment by entozoon** [comment]
And this file.
https://github.com/PaulStoffregen/AltSoftSerial/blob/master/examples/Test/Test.pde

While we're on the topic, why can't you customise the pins when initialising it? like with SoftwareSerial

**Comment by PaulStoffregen** [comment]
You can't choose the pin because AltSoftSerial uses the timer's input capture to receive and output compare to transmit.  The timer inside the chip only has specific pins connected for those functions.

Using the timer is what makes AltSoftSerial different from regular SoftwareSerial.

**Comment by entozoon** [comment]
Aaah that's really interesting, thanks :)

**Comment by julesra** [comment]
It would be good if the Arduino Pro Mini and its pins were added to the table on this page:
https://www.pjrc.com/teensy/td_libs_AltSoftSerial.html

I am using a Pro Mini and didn't know if this library will work, or what pins I should be using. If this library actually depends on the chipset, rather than the type of Arduino board, then it would be more more clear to edit that table and replace the Boards with actual Chipset. That would help noobs like me who don't know if the lib applies for my setup; and it would help people who have other (present & future) boards not listed in the table.

PS: Thanks for this lib! I was having trouble with with multiple SoftwareSerial connections and porting to this AltSoftSerial library required just changing the object initialization :)

**Comment by PaulStoffregen** [comment]
I do not have a Pro Mini.  Can you supply the info for the documentation?

**Comment by julesra** [comment]
Sure. What info do you need ? Just the chipset ?

**Comment by PaulStoffregen** [comment]
What info do you expect to see on the web page?  Probably the pin numbers.

I'm looking to *you* to look at the code, Atmel datasheet, and schematic to figure this out, and for *you* to test and confirm the actual pin numbers.

Then I'll update the page.

If you're expecting me to do all that work, which would also involve actually getting a Pro Mini... well, that's far more than I'm going to do to support Pro Mini.

All I'm willing to do is update the web page, after *you* do all the work to figure it out, and after *you* have actually confirmed it works by testing with an actual Pro Mini.

**Comment by ReallyNiceGuy** [comment]
Sorry to get into this too late.
When I opened the issue, I said that the pro mini will have the same pins
as the uno. I actually used it. I don't get the whole discussion.
If you would be so kind to just say that the pins for the pro mini will be
the same as the uno, this will actually close the issue.

Thank you.

Closed #2 <https://github.com/PaulStoffregen/AltSoftSerial/issues/2>.

—
Reply to this email directly or view it on GitHub
<https://github.com/PaulStoffregen/AltSoftSerial/issues/2#event-483894867>.

**Comment by julesra** [comment]
Hi Paul,

Based on my experience with the Pro Mini, here's the information that I would find useful to see on the https://www.pjrc.com/teensy/td_libs_AltSoftSerial.html page.

Board | Transmit Pin | Receive Pin | Unusable PWM
------------ | ------------- | ------------- | -------------
Pro Mini 5V with Atmega328 | 9 | 8 | ????

I'm fairly new to electronics and to Git contributions, so I wasn't expecting you to do anything, but I was hoping that your experience would be useful with the following: I don't know enough about electronics and your code to be able to answer the following things:
* I don't know what PWM would become unusable Atmega328
* I don't know if this configuration (Tx=9, Rx=8) works for all Atmega328 chips on any Arduino board at both 3.3V and 5V, or just works on the Pro Mini 5V which I have.  (If it applies for all Arduinos with Atmega328 chips, then the table should have a column for "Chip" rather than "Board") 
* I don't know if this applies for other Pro Mini boards which contain Atmega168

Sorry I wish I had more experience in order to answer these questions myself and provide you with a simple and reliable answer !
